#pragma once

#include "GameObject.h"

void CreateYbotAnimationComponent(Netcode::Asset::Model * model, Animation * anim) {
	anim->blackboard.CreateResources(model,
				// states
				{
					{ "Idle",			5,		Netcode::Animation::StateBehaviour::LOOP },
					{ "Forward",		6,		Netcode::Animation::StateBehaviour::LOOP },
					{ "Backward",		7,		Netcode::Animation::StateBehaviour::LOOP },
					{ "Left",			12,		Netcode::Animation::StateBehaviour::LOOP },
					{ "Right",			13,		Netcode::Animation::StateBehaviour::LOOP },
					{ "ForwardLeft",	10,		Netcode::Animation::StateBehaviour::LOOP },
					{ "ForwardRight",	11,		Netcode::Animation::StateBehaviour::LOOP },
					{ "BackwardLeft",	8,		Netcode::Animation::StateBehaviour::LOOP },
					{ "BackwardRight",	9,		Netcode::Animation::StateBehaviour::LOOP },
					{ "JumpStart",		4,		Netcode::Animation::StateBehaviour::ONCE },
					{ "JumpLoop",		3,		Netcode::Animation::StateBehaviour::LOOP },
					{ "JumpLand",		2,		Netcode::Animation::StateBehaviour::ONCE }
				},
				// transitions
			   { 
					{ "Forward",   "Idle",			&Netcode::MovementController::IsIdle,					nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Forward",   "Backward",		&Netcode::MovementController::IsMovingBackward,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Forward",   "Left",			&Netcode::MovementController::IsMovingLeft,				nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Forward",   "Right",			&Netcode::MovementController::IsMovingRight,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Forward",   "ForwardLeft",	&Netcode::MovementController::IsMovingForwardLeft,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Forward",   "ForwardRight",	&Netcode::MovementController::IsMovingForwardRight,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Forward",   "BackwardLeft",	&Netcode::MovementController::IsMovingBackwardLeft,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Forward",   "BackwardRight",	&Netcode::MovementController::IsMovingBackwardRight,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Forward",   "JumpStart",		&Netcode::MovementController::IsJumping,				nullptr,							Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },

					{ "Backward",   "Idle",			&Netcode::MovementController::IsIdle,					nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Backward",   "Forward",		&Netcode::MovementController::IsMovingForward,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Backward",   "Left",			&Netcode::MovementController::IsMovingLeft,				nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Backward",   "Right",		&Netcode::MovementController::IsMovingRight,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Backward",   "ForwardLeft",	&Netcode::MovementController::IsMovingForwardLeft,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Backward",   "ForwardRight",	&Netcode::MovementController::IsMovingForwardRight,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Backward",   "BackwardLeft",	&Netcode::MovementController::IsMovingBackwardLeft,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Backward",   "BackwardRight",&Netcode::MovementController::IsMovingBackwardRight,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Backward",   "JumpStart",	&Netcode::MovementController::IsJumping,				nullptr,							Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },

					{ "Left",   "Idle",				&Netcode::MovementController::IsIdle,					nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Left",   "Forward",			&Netcode::MovementController::IsMovingForward,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Left",   "Backward",			&Netcode::MovementController::IsMovingBackward,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Left",   "Right",			&Netcode::MovementController::IsMovingRight,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Left",   "ForwardLeft",		&Netcode::MovementController::IsMovingForwardLeft,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Left",   "ForwardRight",		&Netcode::MovementController::IsMovingForwardRight,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Left",   "BackwardLeft",		&Netcode::MovementController::IsMovingBackwardLeft,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Left",   "BackwardRight",	&Netcode::MovementController::IsMovingBackwardRight,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Left",   "JumpStart",		&Netcode::MovementController::IsJumping,				nullptr,							Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },

					{ "Right",   "Idle",			&Netcode::MovementController::IsIdle,					nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Right",   "Forward",			&Netcode::MovementController::IsMovingForward,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Right",   "Backward",		&Netcode::MovementController::IsMovingBackward,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Right",   "Left",			&Netcode::MovementController::IsMovingLeft,				nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Right",   "ForwardLeft",		&Netcode::MovementController::IsMovingForwardLeft,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Right",   "ForwardRight",	&Netcode::MovementController::IsMovingForwardRight,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Right",   "BackwardLeft",	&Netcode::MovementController::IsMovingBackwardLeft,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Right",   "BackwardRight",	&Netcode::MovementController::IsMovingBackwardRight,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Right",   "JumpStart",		&Netcode::MovementController::IsJumping,				nullptr,							Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },

					{ "ForwardLeft",   "Idle",			&Netcode::MovementController::IsIdle,				nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardLeft",   "Forward",		&Netcode::MovementController::IsMovingForward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardLeft",   "Backward",		&Netcode::MovementController::IsMovingBackward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardLeft",   "Left",			&Netcode::MovementController::IsMovingLeft,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardLeft",   "Right",			&Netcode::MovementController::IsMovingRight,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardLeft",   "ForwardRight",	&Netcode::MovementController::IsMovingForwardRight,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardLeft",   "BackwardLeft",	&Netcode::MovementController::IsMovingBackwardLeft,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardLeft",   "BackwardRight",	&Netcode::MovementController::IsMovingBackwardRight,nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardLeft",   "JumpStart",		&Netcode::MovementController::IsJumping,			nullptr,							Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },

					{ "ForwardRight",   "Idle",			&Netcode::MovementController::IsIdle,				nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardRight",   "Forward",		&Netcode::MovementController::IsMovingForward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardRight",   "Backward",		&Netcode::MovementController::IsMovingBackward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardRight",   "Left",			&Netcode::MovementController::IsMovingLeft,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardRight",   "Right",		&Netcode::MovementController::IsMovingRight,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardRight",   "ForwardLeft",	&Netcode::MovementController::IsMovingForwardLeft,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardRight",   "BackwardLeft",	&Netcode::MovementController::IsMovingBackwardLeft,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardRight",   "BackwardRight",&Netcode::MovementController::IsMovingBackwardRight,nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "ForwardRight",   "JumpStart",	&Netcode::MovementController::IsJumping,			nullptr,							Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },

					{ "BackwardLeft",   "Idle",			&Netcode::MovementController::IsIdle,				nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardLeft",   "Forward",		&Netcode::MovementController::IsMovingForward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardLeft",   "Backward",		&Netcode::MovementController::IsMovingBackward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardLeft",   "Left",			&Netcode::MovementController::IsMovingLeft,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardLeft",   "Right",		&Netcode::MovementController::IsMovingRight,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardLeft",   "ForwardLeft",	&Netcode::MovementController::IsMovingForwardLeft,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardLeft",   "ForwardRight",	&Netcode::MovementController::IsMovingForwardRight,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardLeft",   "BackwardRight",&Netcode::MovementController::IsMovingBackwardRight,nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardLeft",   "JumpStart",	&Netcode::MovementController::IsJumping,			nullptr,							Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },

					{ "BackwardRight",   "Idle",		&Netcode::MovementController::IsIdle,				nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardRight",   "Forward",		&Netcode::MovementController::IsMovingForward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardRight",   "Backward",	&Netcode::MovementController::IsMovingBackward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardRight",   "Left",		&Netcode::MovementController::IsMovingLeft,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardRight",   "Right",		&Netcode::MovementController::IsMovingRight,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardRight",   "ForwardLeft",	&Netcode::MovementController::IsMovingForwardLeft,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardRight",   "ForwardRight",&Netcode::MovementController::IsMovingForwardRight,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardRight",   "BackwardLeft",&Netcode::MovementController::IsMovingBackwardLeft,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "BackwardRight",   "JumpStart",	&Netcode::MovementController::IsJumping,			nullptr,							Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },

					{ "Idle",	   "Forward",			&Netcode::MovementController::IsMovingForward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Idle",	   "Backward",			&Netcode::MovementController::IsMovingBackward,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Idle",	   "Left",				&Netcode::MovementController::IsMovingLeft,			nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Idle",	   "Right",				&Netcode::MovementController::IsMovingRight,		nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Idle",	   "ForwardLeft",		&Netcode::MovementController::IsMovingForwardLeft,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Idle",	   "ForwardRight",		&Netcode::MovementController::IsMovingForwardRight,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Idle",	   "BackwardLeft",		&Netcode::MovementController::IsMovingBackwardLeft,	nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Idle",	   "BackwardRight",		&Netcode::MovementController::IsMovingBackwardRight,nullptr,							Netcode::Animation::TransitionBehaviour::LERP },
					{ "Idle",	   "JumpStart",			&Netcode::MovementController::IsJumping,			nullptr,							Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },

					{ "JumpStart", "JumpLoop",	&Netcode::MovementController::IsJumping,		&Netcode::Animation::AnimationState::IsFinished,	Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },
					{ "JumpStart", "JumpLand",	&Netcode::MovementController::IsOnGround, 		nullptr,										Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },
					{ "JumpLoop",  "JumpLand",	&Netcode::MovementController::IsOnGround,		nullptr,										Netcode::Animation::TransitionBehaviour::STOP_AND_LERP },
					{ "JumpLand",  "Idle",		nullptr,									&Netcode::Animation::AnimationState::IsFinished,	Netcode::Animation::TransitionBehaviour::LERP },
			   });
}