namespace EggEditor2{

	[bindable]
	[default_interface]
	runtimeclass AssetUIDataContext : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		Windows.UI.Color GradientStart;
		Windows.UI.Color GradientStop;
		String OverlayText;
		Windows.UI.Xaml.Controls.Symbol AssetIcon;
		Int32 EditState;

		AssetUIDataContext();

	}

}