import "AssetUIDataContext.idl";
import "IAsset.idl";

namespace EggEditor2{

	[bindable]
	[default_interface]
	runtimeclass AssetDataContext : Windows.UI.Xaml.Data.INotifyPropertyChanged, IAsset {

		Int32 Type;
		AssetUIDataContext UI{ get; };

		AssetDataContext();
		AssetDataContext(Int32 type);

	}

}