namespace EggEditor2{

	interface IAsset {
		
		String Name;
		IAsset ParentFolder;
		Boolean IsDirty;
		Boolean IsAsset{ get; };
		Boolean IsContentDirty{ get; };
		Windows.Foundation.Collections.IObservableVector<IAsset> Children{ get; };

		void AddChild(IAsset asset);

	}

}
