import "ProjectFolderUIDataContext.idl";
import "IAsset.idl";

namespace EggEditor2{

	[bindable]
	[default_interface]
	runtimeclass ProjectFolderDataContext : Windows.UI.Xaml.Data.INotifyPropertyChanged, IAsset {
		String FilePath;
		Int32 FolderId;
		ProjectFolderUIDataContext UI{ get; };

		void InsertFolder(IAsset asset);
		void InsertAsset(IAsset asset);

		ProjectFolderDataContext();
	}

}