namespace NetcodeAssetEditor
{
    [bindable]
    [default_interface]
    runtimeclass DC_Vector3Control : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        DC_Vector3Control();

        Windows.Foundation.Numerics.Vector3 VectorValue;

        Single ValueX;
        Single ValueY;
        Single ValueZ;
    }

    [default_interface]
    runtimeclass Vector3Control : Windows.UI.Xaml.Controls.UserControl
    {
        Vector3Control();

        static Windows.UI.Xaml.DependencyProperty ValueProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty IsReadOnlyProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty MinValueProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty MaxValueProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty StepScaleProperty{ get; };

        Windows.Foundation.Numerics.Vector3 Value;
        Boolean IsReadOnly;
        Double MinValue;
        Double MaxValue;
        Double StepScale;
    }
}
