namespace NetcodeAssetEditor
{
    [bindable]
    [default_interface]
    runtimeclass DC_Vector4Control : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        DC_Vector4Control();

        IInspectable VectorValue;

        Single ValueX;
        Single ValueY;
        Single ValueZ;
        Single ValueW;
    }

   // delegate void Vector4ChangedDelegate(Windows.Foundation.Numerics.Vector4 newValue);

    [default_interface]
    runtimeclass Vector4Control : Windows.UI.Xaml.Controls.UserControl
    {
        Vector4Control();

        static Windows.UI.Xaml.DependencyProperty ValueProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty IsReadOnlyProperty{ get; };

        //event Vector4ChangedDelegate ValueChanged;

        IInspectable Value;
        Boolean IsReadOnly;
    }
}
