//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "UC_GameObject.xaml.h"

void ::EggEditor::UC_GameObject::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///UC_GameObject.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::EggEditor::UC_GameObject::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            ::Windows::UI::Xaml::Controls::Grid^ element2 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(element2))->DragStarting += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^>(this, (void (::EggEditor::UC_GameObject::*)
                (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^))&UC_GameObject::Grid_DragStarting);
            (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(element2))->DragOver += ref new ::Windows::UI::Xaml::DragEventHandler(this, (void (::EggEditor::UC_GameObject::*)
                (::Platform::Object^, ::Windows::UI::Xaml::DragEventArgs^))&UC_GameObject::Grid_DragOver);
            (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(element2))->Drop += ref new ::Windows::UI::Xaml::DragEventHandler(this, (void (::EggEditor::UC_GameObject::*)
                (::Platform::Object^, ::Windows::UI::Xaml::DragEventArgs^))&UC_GameObject::Grid_Drop);
        }
        break;
    case 3:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element3 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::EggEditor::UC_GameObject::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&UC_GameObject::CtxRenameBtn_OnClick);
        }
        break;
    case 4:
        {
            ::Windows::UI::Xaml::Controls::TextBox^ element4 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(element4))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::EggEditor::UC_GameObject::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&UC_GameObject::TextBox_KeyDown);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::EggEditor::UC_GameObject::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


