//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "UC_Properties.xaml.h"
#include "UC_TransformComponent.xaml.h"
#include "UC_ScriptComponent.xaml.h"
#include "UC_MeshComponent.xaml.h"

void ::EggEditor::UC_Properties::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///UC_Properties.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::EggEditor::UC_Properties::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->transformComponentControl = safe_cast<::EggEditor::UC_TransformComponent^>(__target);
        }
        break;
    case 3:
        {
            this->scriptComponentControl = safe_cast<::EggEditor::UC_ScriptComponent^>(__target);
        }
        break;
    case 4:
        {
            this->meshComponentControl = safe_cast<::EggEditor::UC_MeshComponent^>(__target);
        }
        break;
    case 5:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element5 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element5))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::EggEditor::UC_Properties::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&UC_Properties::CtxAddTransformComponentBtn_OnClick);
        }
        break;
    case 6:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element6 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element6))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::EggEditor::UC_Properties::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&UC_Properties::CtxAddScriptComponentBtn_OnClick);
        }
        break;
    case 7:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element7 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element7))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::EggEditor::UC_Properties::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&UC_Properties::CtxAddMeshComponentBtn_OnClick);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::EggEditor::UC_Properties::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


