#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace EggEditor {
    ref class UC_TransformComponent;
    ref class UC_ScriptComponent;
    ref class UC_MeshComponent;
}

namespace EggEditor
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class UC_Properties : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class UC_Properties_obj1_Bindings;
    
        private: ::EggEditor::UC_TransformComponent^ transformComponentControl;
        private: ::EggEditor::UC_ScriptComponent^ scriptComponentControl;
        private: ::EggEditor::UC_MeshComponent^ meshComponentControl;
    };
}

