//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "UC_ProjectFolder.xaml.h"

void ::EggEditor::UC_ProjectFolder::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///UC_ProjectFolder.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::EggEditor::UC_ProjectFolder::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->mainGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(this->mainGrid))->DragStarting += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^>(this, (void (::EggEditor::UC_ProjectFolder::*)
                (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^))&UC_ProjectFolder::ProjectFolderDragStarting);
            (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(this->mainGrid))->DragOver += ref new ::Windows::UI::Xaml::DragEventHandler(this, (void (::EggEditor::UC_ProjectFolder::*)
                (::Platform::Object^, ::Windows::UI::Xaml::DragEventArgs^))&UC_ProjectFolder::ProjectFolderDragOver);
            (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(this->mainGrid))->Drop += ref new ::Windows::UI::Xaml::DragEventHandler(this, (void (::EggEditor::UC_ProjectFolder::*)
                (::Platform::Object^, ::Windows::UI::Xaml::DragEventArgs^))&UC_ProjectFolder::ProjectFolderDrop);
        }
        break;
    case 3:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element3 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::EggEditor::UC_ProjectFolder::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&UC_ProjectFolder::MenuFlyoutItem_Click);
        }
        break;
    case 4:
        {
            this->projectFolderName = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 5:
        {
            ::Windows::UI::Xaml::Controls::TextBox^ element5 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(element5))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::EggEditor::UC_ProjectFolder::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&UC_ProjectFolder::TextBox_KeyDown);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(element5))->FocusDisengaged += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::Control^, ::Windows::UI::Xaml::Controls::FocusDisengagedEventArgs^>(this, (void (::EggEditor::UC_ProjectFolder::*)
                (::Windows::UI::Xaml::Controls::Control^, ::Windows::UI::Xaml::Controls::FocusDisengagedEventArgs^))&UC_ProjectFolder::TextBox_FocusDisengaged);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::EggEditor::UC_ProjectFolder::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


