//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "UC_ScriptComponent.xaml.h"

void ::EggEditor::UC_ScriptComponent::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///UC_ScriptComponent.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::EggEditor::UC_ScriptComponent::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->scriptRefTextBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->scriptRefTextBox))->DragOver += ref new ::Windows::UI::Xaml::DragEventHandler(this, (void (::EggEditor::UC_ScriptComponent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::DragEventArgs^))&UC_ScriptComponent::TextBox_DragOver);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->scriptRefTextBox))->Drop += ref new ::Windows::UI::Xaml::DragEventHandler(this, (void (::EggEditor::UC_ScriptComponent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::DragEventArgs^))&UC_ScriptComponent::TextBox_Drop);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::EggEditor::UC_ScriptComponent::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


