//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "UC_TransformComponent.xaml.h"

void ::EggEditor::UC_TransformComponent::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///UC_TransformComponent.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::EggEditor::UC_TransformComponent, ::XamlBindingInfo::XamlBindingTrackingBase>
    , public ::XamlBindingInfo::IXamlBindingTracking
{
public:
    UC_TransformComponent_obj1_Bindings()
    {
        InitializeTracking(this);
    }

private:
    ~UC_TransformComponent_obj1_Bindings()
    {
        ReleaseAllListeners();
    }

public:

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 2: // UC_TransformComponent.xaml line 36
                this->obj2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                this->obj2->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(
                        [this] (::Platform::Object^ sender, ::Windows::UI::Xaml::RoutedEventArgs^ e)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                if (this->GetDataRoot() != nullptr)
                                {
                                    if (this->GetDataRoot()->Component != nullptr)
                                    {
                                        this->GetDataRoot()->Component->PositionX = (::default::float32) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::default::float32::typeid, this->obj2->Text);
                                    }
                                }
                            }
                        });
                break;
            case 3: // UC_TransformComponent.xaml line 37
                this->obj3 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                this->obj3->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(
                        [this] (::Platform::Object^ sender, ::Windows::UI::Xaml::RoutedEventArgs^ e)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                if (this->GetDataRoot() != nullptr)
                                {
                                    if (this->GetDataRoot()->Component != nullptr)
                                    {
                                        this->GetDataRoot()->Component->PositionY = (::default::float32) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::default::float32::typeid, this->obj3->Text);
                                    }
                                }
                            }
                        });
                break;
            case 4: // UC_TransformComponent.xaml line 38
                this->obj4 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                this->obj4->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(
                        [this] (::Platform::Object^ sender, ::Windows::UI::Xaml::RoutedEventArgs^ e)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                if (this->GetDataRoot() != nullptr)
                                {
                                    if (this->GetDataRoot()->Component != nullptr)
                                    {
                                        this->GetDataRoot()->Component->PositionZ = (::default::float32) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::default::float32::typeid, this->obj4->Text);
                                    }
                                }
                            }
                        });
                break;
            case 5: // UC_TransformComponent.xaml line 40
                this->obj5 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                this->obj5->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(
                        [this] (::Platform::Object^ sender, ::Windows::UI::Xaml::RoutedEventArgs^ e)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                if (this->GetDataRoot() != nullptr)
                                {
                                    if (this->GetDataRoot()->Component != nullptr)
                                    {
                                        this->GetDataRoot()->Component->RotationX = (::default::float32) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::default::float32::typeid, this->obj5->Text);
                                    }
                                }
                            }
                        });
                break;
            case 6: // UC_TransformComponent.xaml line 41
                this->obj6 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                this->obj6->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(
                        [this] (::Platform::Object^ sender, ::Windows::UI::Xaml::RoutedEventArgs^ e)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                if (this->GetDataRoot() != nullptr)
                                {
                                    if (this->GetDataRoot()->Component != nullptr)
                                    {
                                        this->GetDataRoot()->Component->RotationY = (::default::float32) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::default::float32::typeid, this->obj6->Text);
                                    }
                                }
                            }
                        });
                break;
            case 7: // UC_TransformComponent.xaml line 42
                this->obj7 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                this->obj7->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(
                        [this] (::Platform::Object^ sender, ::Windows::UI::Xaml::RoutedEventArgs^ e)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                if (this->GetDataRoot() != nullptr)
                                {
                                    if (this->GetDataRoot()->Component != nullptr)
                                    {
                                        this->GetDataRoot()->Component->RotationZ = (::default::float32) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::default::float32::typeid, this->obj7->Text);
                                    }
                                }
                            }
                        });
                break;
            case 8: // UC_TransformComponent.xaml line 44
                this->obj8 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                this->obj8->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(
                        [this] (::Platform::Object^ sender, ::Windows::UI::Xaml::RoutedEventArgs^ e)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                if (this->GetDataRoot() != nullptr)
                                {
                                    if (this->GetDataRoot()->Component != nullptr)
                                    {
                                        this->GetDataRoot()->Component->ScaleX = (::default::float32) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::default::float32::typeid, this->obj8->Text);
                                    }
                                }
                            }
                        });
                break;
            case 9: // UC_TransformComponent.xaml line 45
                this->obj9 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                this->obj9->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(
                        [this] (::Platform::Object^ sender, ::Windows::UI::Xaml::RoutedEventArgs^ e)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                if (this->GetDataRoot() != nullptr)
                                {
                                    if (this->GetDataRoot()->Component != nullptr)
                                    {
                                        this->GetDataRoot()->Component->ScaleY = (::default::float32) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::default::float32::typeid, this->obj9->Text);
                                    }
                                }
                            }
                        });
                break;
            case 10: // UC_TransformComponent.xaml line 46
                this->obj10 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                this->obj10->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(
                        [this] (::Platform::Object^ sender, ::Windows::UI::Xaml::RoutedEventArgs^ e)
                        {
                            if (this->IsInitialized())
                            {
                                // Update Two Way binding
                                if (this->GetDataRoot() != nullptr)
                                {
                                    if (this->GetDataRoot()->Component != nullptr)
                                    {
                                        this->GetDataRoot()->Component->ScaleZ = (::default::float32) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::default::float32::typeid, this->obj10->Text);
                                    }
                                }
                            }
                        });
                break;
        }
    }

    void Disable(int lineNumber, int columnNumber)
    {
        if (lineNumber == 36 && columnNumber == 47)
        {
            isobj2TextDisabled = true;
        }
        else if (lineNumber == 37 && columnNumber == 47)
        {
            isobj3TextDisabled = true;
        }
        else if (lineNumber == 38 && columnNumber == 47)
        {
            isobj4TextDisabled = true;
        }
        else if (lineNumber == 40 && columnNumber == 47)
        {
            isobj5TextDisabled = true;
        }
        else if (lineNumber == 41 && columnNumber == 47)
        {
            isobj6TextDisabled = true;
        }
        else if (lineNumber == 42 && columnNumber == 47)
        {
            isobj7TextDisabled = true;
        }
        else if (lineNumber == 44 && columnNumber == 47)
        {
            isobj8TextDisabled = true;
        }
        else if (lineNumber == 45 && columnNumber == 47)
        {
            isobj9TextDisabled = true;
        }
        else if (lineNumber == 46 && columnNumber == 47)
        {
            isobj10TextDisabled = true;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
        return;
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        *nextPhase = -1;
    }

private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::TextBox^ obj2;
    ::Windows::UI::Xaml::Controls::TextBox^ obj3;
    ::Windows::UI::Xaml::Controls::TextBox^ obj4;
    ::Windows::UI::Xaml::Controls::TextBox^ obj5;
    ::Windows::UI::Xaml::Controls::TextBox^ obj6;
    ::Windows::UI::Xaml::Controls::TextBox^ obj7;
    ::Windows::UI::Xaml::Controls::TextBox^ obj8;
    ::Windows::UI::Xaml::Controls::TextBox^ obj9;
    ::Windows::UI::Xaml::Controls::TextBox^ obj10;

    // Static fields for each binding's enabled/disabled state
    static bool isobj2TextDisabled;
    static bool isobj3TextDisabled;
    static bool isobj4TextDisabled;
    static bool isobj5TextDisabled;
    static bool isobj6TextDisabled;
    static bool isobj7TextDisabled;
    static bool isobj8TextDisabled;
    static bool isobj9TextDisabled;
    static bool isobj10TextDisabled;
    
    // Fields for binding tracking.

    // Update methods for each path node used in binding steps.
    void Update_(::EggEditor::UC_TransformComponent^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Component(obj->Component, phase);
            }
        }
    }
    void Update_Component(::EggEditor::VM_TransformComponent^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0))) != 0)
            {
                this->Update_Component_PositionX(obj->PositionX, phase);
                this->Update_Component_PositionY(obj->PositionY, phase);
                this->Update_Component_PositionZ(obj->PositionZ, phase);
                this->Update_Component_RotationX(obj->RotationX, phase);
                this->Update_Component_RotationY(obj->RotationY, phase);
                this->Update_Component_RotationZ(obj->RotationZ, phase);
                this->Update_Component_ScaleX(obj->ScaleX, phase);
                this->Update_Component_ScaleY(obj->ScaleY, phase);
                this->Update_Component_ScaleZ(obj->ScaleZ, phase);
            }
        }
    }
    void Update_Component_PositionX(::default::float32 obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // UC_TransformComponent.xaml line 36
            if (!isobj2TextDisabled)
            {
                Set_Windows_UI_Xaml_Controls_TextBox_Text(this->obj2, obj.ToString(), nullptr);
            }
        }
    }
    void Update_Component_PositionY(::default::float32 obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // UC_TransformComponent.xaml line 37
            if (!isobj3TextDisabled)
            {
                Set_Windows_UI_Xaml_Controls_TextBox_Text(this->obj3, obj.ToString(), nullptr);
            }
        }
    }
    void Update_Component_PositionZ(::default::float32 obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // UC_TransformComponent.xaml line 38
            if (!isobj4TextDisabled)
            {
                Set_Windows_UI_Xaml_Controls_TextBox_Text(this->obj4, obj.ToString(), nullptr);
            }
        }
    }
    void Update_Component_RotationX(::default::float32 obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // UC_TransformComponent.xaml line 40
            if (!isobj5TextDisabled)
            {
                Set_Windows_UI_Xaml_Controls_TextBox_Text(this->obj5, obj.ToString(), nullptr);
            }
        }
    }
    void Update_Component_RotationY(::default::float32 obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // UC_TransformComponent.xaml line 41
            if (!isobj6TextDisabled)
            {
                Set_Windows_UI_Xaml_Controls_TextBox_Text(this->obj6, obj.ToString(), nullptr);
            }
        }
    }
    void Update_Component_RotationZ(::default::float32 obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // UC_TransformComponent.xaml line 42
            if (!isobj7TextDisabled)
            {
                Set_Windows_UI_Xaml_Controls_TextBox_Text(this->obj7, obj.ToString(), nullptr);
            }
        }
    }
    void Update_Component_ScaleX(::default::float32 obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // UC_TransformComponent.xaml line 44
            if (!isobj8TextDisabled)
            {
                Set_Windows_UI_Xaml_Controls_TextBox_Text(this->obj8, obj.ToString(), nullptr);
            }
        }
    }
    void Update_Component_ScaleY(::default::float32 obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // UC_TransformComponent.xaml line 45
            if (!isobj9TextDisabled)
            {
                Set_Windows_UI_Xaml_Controls_TextBox_Text(this->obj9, obj.ToString(), nullptr);
            }
        }
    }
    void Update_Component_ScaleZ(::default::float32 obj, int phase)
    {
        if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
        {
            // UC_TransformComponent.xaml line 46
            if (!isobj10TextDisabled)
            {
                Set_Windows_UI_Xaml_Controls_TextBox_Text(this->obj10, obj.ToString(), nullptr);
            }
        }
    }

    virtual void ReleaseAllListeners() override
    {
    }

    virtual void PropertyChanged(Platform::Object^ sender, ::Windows::UI::Xaml::Data::PropertyChangedEventArgs^ e) override
    {
    }

    void CollectionChanged(::Platform::Object^ sender, ::Windows::UI::Xaml::Interop::NotifyCollectionChangedEventArgs^ e)
    {
    }

    void VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)
    {
    }

    void MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)
    {
    }

    void DependencyPropertyChanged(::Windows::UI::Xaml::DependencyObject^ sender, ::Windows::UI::Xaml::DependencyProperty^ prop)
    {
        if (sender != nullptr)
        {
        }
    }

    static void Set_Windows_UI_Xaml_Controls_TextBox_Text(::Windows::UI::Xaml::Controls::TextBox^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
};

    // Initializing static fields for each binding's enabled/disabled state
bool EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings::isobj2TextDisabled = false;
bool EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings::isobj3TextDisabled = false;
bool EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings::isobj4TextDisabled = false;
bool EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings::isobj5TextDisabled = false;
bool EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings::isobj6TextDisabled = false;
bool EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings::isobj7TextDisabled = false;
bool EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings::isobj8TextDisabled = false;
bool EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings::isobj9TextDisabled = false;
bool EggEditor::UC_TransformComponent::UC_TransformComponent_obj1_Bindings::isobj10TextDisabled = false;

void ::EggEditor::UC_TransformComponent::Connect(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced 
    __target;               // unreferenced
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::EggEditor::UC_TransformComponent::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1: // UC_TransformComponent.xaml line 1
            {
                ::Windows::UI::Xaml::Controls::UserControl^ element1 = safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(__target);
                UC_TransformComponent_obj1_Bindings* objBindings = new UC_TransformComponent_obj1_Bindings();
                objBindings->SetDataRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                this->Bindings = bindings;
                element1->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(bindings, &::XamlBindingInfo::XamlBindings::Loading);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element1, bindings);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


